/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Culculator;

/**
 *
 * @author Tasfuye
 */
public class Culculator extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Culculator.class.getName());
     String EnterNum1;
     String EnterNum2;
     String op;
    
    public Culculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtResult = new javax.swing.JTextField();
        jBtnPM = new javax.swing.JButton();
        jBnBS = new javax.swing.JButton();
        jBtnCE = new javax.swing.JButton();
        jBtnC = new javax.swing.JButton();
        jBtnPlus = new javax.swing.JButton();
        jBtnDigit7 = new javax.swing.JButton();
        jBtnDigit8 = new javax.swing.JButton();
        jBtnDigit9 = new javax.swing.JButton();
        jBtnDigit6 = new javax.swing.JButton();
        jBtnMinus = new javax.swing.JButton();
        jBtnDigit4 = new javax.swing.JButton();
        jBtnDigit5 = new javax.swing.JButton();
        jBtnDigit1 = new javax.swing.JButton();
        jBtnDigit2 = new javax.swing.JButton();
        jBtnDigit3 = new javax.swing.JButton();
        jBtnDiv = new javax.swing.JButton();
        jBtnDigit0 = new javax.swing.JButton();
        jBtnDot = new javax.swing.JButton();
        jBtnMult = new javax.swing.JButton();
        jBtnEq = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtResult.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jtxtResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtResult.addActionListener(this::jtxtResultActionPerformed);
        getContentPane().add(jtxtResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 320, 70));

        jBtnPM.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jBtnPM.setText("+/-");
        jBtnPM.addActionListener(this::jBtnPMActionPerformed);
        getContentPane().add(jBtnPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 74, 74));

        jBnBS.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jBnBS.setText("B");
        jBnBS.addActionListener(this::jBnBSActionPerformed);
        getContentPane().add(jBnBS, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 74, 74));

        jBtnCE.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jBtnCE.setText("CE");
        getContentPane().add(jBtnCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 74, 74));

        jBtnC.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jBtnC.setText("C");
        jBtnC.addActionListener(this::jBtnCActionPerformed);
        getContentPane().add(jBtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 74, 74));

        jBtnPlus.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jBtnPlus.setText("+");
        jBtnPlus.addActionListener(this::jBtnPlusActionPerformed);
        getContentPane().add(jBtnPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 74, 74));

        jBtnDigit7.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jBtnDigit7.setText("7");
        jBtnDigit7.addActionListener(this::jBtnDigit7ActionPerformed);
        getContentPane().add(jBtnDigit7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 74, 74));

        jBtnDigit8.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jBtnDigit8.setText("8");
        jBtnDigit8.addActionListener(this::jBtnDigit8ActionPerformed);
        getContentPane().add(jBtnDigit8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 74, 74));

        jBtnDigit9.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jBtnDigit9.setText("9");
        jBtnDigit9.addActionListener(this::jBtnDigit9ActionPerformed);
        getContentPane().add(jBtnDigit9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 74, 74));

        jBtnDigit6.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jBtnDigit6.setText("6");
        jBtnDigit6.addActionListener(this::jBtnDigit6ActionPerformed);
        getContentPane().add(jBtnDigit6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 74, 74));

        jBtnMinus.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jBtnMinus.setText("-");
        jBtnMinus.addActionListener(this::jBtnMinusActionPerformed);
        getContentPane().add(jBtnMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 74, 74));

        jBtnDigit4.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jBtnDigit4.setText("4");
        jBtnDigit4.addActionListener(this::jBtnDigit4ActionPerformed);
        getContentPane().add(jBtnDigit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 74, 74));

        jBtnDigit5.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jBtnDigit5.setText("5");
        jBtnDigit5.addActionListener(this::jBtnDigit5ActionPerformed);
        getContentPane().add(jBtnDigit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 74, 74));

        jBtnDigit1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jBtnDigit1.setText("1");
        jBtnDigit1.addActionListener(this::jBtnDigit1ActionPerformed);
        getContentPane().add(jBtnDigit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 74, 74));

        jBtnDigit2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jBtnDigit2.setText("2");
        jBtnDigit2.addActionListener(this::jBtnDigit2ActionPerformed);
        getContentPane().add(jBtnDigit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 74, 74));

        jBtnDigit3.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jBtnDigit3.setText("3");
        jBtnDigit3.addActionListener(this::jBtnDigit3ActionPerformed);
        getContentPane().add(jBtnDigit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 74, 74));

        jBtnDiv.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jBtnDiv.setText("/");
        jBtnDiv.addActionListener(this::jBtnDivActionPerformed);
        getContentPane().add(jBtnDiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 74, 74));

        jBtnDigit0.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jBtnDigit0.setText("0");
        jBtnDigit0.addActionListener(this::jBtnDigit0ActionPerformed);
        getContentPane().add(jBtnDigit0, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 74, 74));

        jBtnDot.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jBtnDot.setText(".");
        getContentPane().add(jBtnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 74, 74));

        jBtnMult.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jBtnMult.setText("*");
        jBtnMult.addActionListener(this::jBtnMultActionPerformed);
        getContentPane().add(jBtnMult, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 74, 74));

        jBtnEq.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jBtnEq.setText("=");
        jBtnEq.addActionListener(this::jBtnEqActionPerformed);
        getContentPane().add(jBtnEq, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 74, 74));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void EnterNumbers(String q){
  String Nums = jtxtResult.getText() + q;
   jtxtResult.setText(Nums);
}
    private void jBtnPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnPMActionPerformed

    private void jBtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCActionPerformed

    private void jBtnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPlusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnPlusActionPerformed

    private void jBtnDigit9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDigit9ActionPerformed
               EnterNumbers("9");
    }//GEN-LAST:event_jBtnDigit9ActionPerformed

    private void jBtnDigit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDigit6ActionPerformed
            EnterNumbers("6");
    }//GEN-LAST:event_jBtnDigit6ActionPerformed

    private void jBtnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMinusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnMinusActionPerformed

    private void jBtnDigit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDigit3ActionPerformed
          EnterNumbers("3");
    }//GEN-LAST:event_jBtnDigit3ActionPerformed

    private void jBtnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnDivActionPerformed

    private void jBtnMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnMultActionPerformed

    private void jBtnEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnEqActionPerformed

    private void jBtnDigit8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDigit8ActionPerformed
                 EnterNumbers("8");
    }//GEN-LAST:event_jBtnDigit8ActionPerformed

    private void jBtnDigit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDigit1ActionPerformed
           EnterNumbers("1");
    }//GEN-LAST:event_jBtnDigit1ActionPerformed

    private void jBtnDigit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDigit5ActionPerformed
           EnterNumbers("5");
    }//GEN-LAST:event_jBtnDigit5ActionPerformed

    private void jBtnDigit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDigit2ActionPerformed
         EnterNumbers("2");
    }//GEN-LAST:event_jBtnDigit2ActionPerformed

    private void jBtnDigit0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDigit0ActionPerformed
                      EnterNumbers("0");
    }//GEN-LAST:event_jBtnDigit0ActionPerformed

    private void jtxtResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtResultActionPerformed

    private void jBnBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnBSActionPerformed
       
    }//GEN-LAST:event_jBnBSActionPerformed

    private void jBtnDigit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDigit7ActionPerformed
           EnterNumbers("7");        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnDigit7ActionPerformed

    private void jBtnDigit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDigit4ActionPerformed
            EnterNumbers("4");
    }//GEN-LAST:event_jBtnDigit4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Culculator().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBnBS;
    private javax.swing.JButton jBtnC;
    private javax.swing.JButton jBtnCE;
    private javax.swing.JButton jBtnDigit0;
    private javax.swing.JButton jBtnDigit1;
    private javax.swing.JButton jBtnDigit2;
    private javax.swing.JButton jBtnDigit3;
    private javax.swing.JButton jBtnDigit4;
    private javax.swing.JButton jBtnDigit5;
    private javax.swing.JButton jBtnDigit6;
    private javax.swing.JButton jBtnDigit7;
    private javax.swing.JButton jBtnDigit8;
    private javax.swing.JButton jBtnDigit9;
    private javax.swing.JButton jBtnDiv;
    private javax.swing.JButton jBtnDot;
    private javax.swing.JButton jBtnEq;
    private javax.swing.JButton jBtnMinus;
    private javax.swing.JButton jBtnMult;
    private javax.swing.JButton jBtnPM;
    private javax.swing.JButton jBtnPlus;
    private javax.swing.JTextField jtxtResult;
    // End of variables declaration//GEN-END:variables
}
